apiVersion: v1
kind: Service
metadata:
  labels:
    app: lapis-blogx
  name: lapis-blogx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      # Container Port
      targetPort: 8080
      protocol: TCP
  selector:
    app: lapis-blogx
